### ISSUE TITLE
UI Lag

### ISSUE THREAD

**Issue by ColeMaurer** [ColeMaurer/FULLSTACK-APP#5]
The webpage has become borderline unresponsive after attempting to add indicators to the stock list. Part 11 of the [fullstack-app tutorial](https://www.youtube.com/watch?v=ryqsCbVSHtY&list=PLvzuUVysUFOuoRna8KhschkVVUo2E2g6G&index=12&t=1687s) is where these indicators were introduced. 
It is hard to say where exactly the issue is, but the main files that were modified were the Index.html file, and the Main.py file. In particular, the `for` loop in Index.html starting on line 36, and the app database operations and data returns from lines 49-61 of the Main.py file.

**Comment by danevs-10** [comment]
On it boss o7

**Comment by ColeMaurer** [comment]
Ladies and gentleman we got em.
